### ISSUE TITLE
Tags?

### ISSUE THREAD

**Issue by john-cj** [artstisen/AHOY#1]
This app is the absolute rock star and it's a wonder that it seems almost nobody aware of its existence. 

The single thing I don't understand, however, is the way how is it possible to use it without tags. For example, I have a bunch of notes about programming, another bunch is about books, and the third bunch is about movies. How is it possible to see all the notes about movies? I need at least 3 tags. Yeah, I can use search, but it's not always convenient.

**Comment by artstisen** [comment]
Hi John, thank you for your feedback, I'm pleased to hear you like the software! Yes, tags would be a nice feature -I have added your request to my to-do list and will aim to include it in the next release along a few other features for categorizing entries :)

**Comment by artstisen** [comment]
Hi John, I have added the option to create categories from within the pinned list (and search result) in the latest release (v1.5.5.2). You can set an entry to act as a category, and add other entries to be part of that category. For example an entry called "Music", will appear in the search result, with a small icon indicating that it is also a category, with the possibility to expand it (by clicking it) and view all its related entries (Jazz, Rock, Pop etc.). The easiest way to work with categories is to pin your entry to the pinned list, right click and select "New category" from the context menu. Right click other entries in the pinned list or search result to add them to the new category.

A range of options will appear when right clicking a category in the pinned list. 
-Click categories in the pinned list to expand or collapse them -the expanded/collapsed state is saved across sessions.

**Comment by artstisen** [comment]
![category-animation1](https://user-images.githubusercontent.com/46990511/77246039-a9fff300-6c23-11ea-993b-39675214fbcb.gif)
